/*************************************************************/
/*   P15-F09     Les 144-15          Uitwerking opdracht 1   */
/*   compiler met /EHa                                      */
/*                                                          */
/************************************************************/

#include <iostream>       // Bibliotheek met cin, cout, cerr

using namespace std;

int main (void)
{

	int a = rand(); 

	printf( "getal1 = : %d\n", a );

	int b = rand(); 

	printf( "getal1 = : %d\n", b );
	exit(1) ;
}
