
/************************************************************/
/*   P15-F06     Les 144-15          Uitwerking opdracht 6  */
/*                                                          */
/*                                                          */
/************************************************************/


#include <iostream>       // Bibliotheek met cin, cout, cerr

using namespace std;

int main (void)
{



	int  a = 4;
	int  b = 0;
	
	int c = a / b;
  
	exit(1) ;
}
