
/************************************************************/
/*   P08-F05B     Programma voor het testen van dirksen.h   */
/************************************************************/


#include <iostream>       // Bibliotheek met cin, cout, cerr
#include <conio.h>          // Bibliotheek met putch en getch
#include <dirksen.h>        // Bibliotheek voor Dirksen-cursus


using namespace std;

int main (void)                 // Begin hoofdfunctie P08-F05B
{
  WisBeeld ;

  cout << "Test van header-file dirksen.h" ;

  PauzeStop ;
}                               // Einde hoofdfunctie P08-F05B
